# Generated by Django 4.2.7 on 2024-01-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='borrow_book',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='return_book',
        ),
    ]
