# Generated by Django 4.2.7 on 2024-01-03 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_remove_borrow_user_borrow_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='users',
        ),
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
